---
- name: Configure Vault as Certificate Authority and enable HTTPS
  hosts: vault
  become: true
  gather_facts: true

  vars_files:
    - ../vault/secrets.yml

  roles:
    - role: configure_vault